version: '3'
services:
    web:
        image: nginx
        container_name: lotto-nginx
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
            - 8070:80
        restart: always
        depends_on:
            - php
            - db
    php:
        image: lotto
        container_name: lotto-web
        build:
            context: ./.docker
            args:
                APP_ENV: ${APP_ENV}
        restart: always
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - .:/var/www/html
    scheduler:
        image: lotto
        container_name: lotto-scheduler
        restart: unless-stopped
        links:
            - db
        volumes:
            - ./:/var/www/html
        environment:
            CONTAINER_ROLE: scheduler
            TZ: "Europe/Warsaw"
    db:
        image: postgres:14.3
        container_name: lotto-db
        restart: always
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/
volumes:
    postgres-data:
